defaultProject: hub-32-dataw-dev-1
defaultLocation: US
defaultDataset: hub_32_dataw_dev_1
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
vars:
    ENV: "dev"
    PROJ_BILL_DUMP: "dump-billing-export1"
    DATASET_BILL_DUMP: "billing_dataset"
    BILLING_ACCOUNT: "01C187-3B1837-998842"
    GEMINI_CNX: "bq_gemini_connection"




